# Generated by Django 3.2.2 on 2021-05-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_of', models.IntegerField()),
                ('time', models.IntegerField()),
                ('score_to_pass', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
