# Generated by Django 3.2.2 on 2021-05-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='number_of',
            new_name='number_of_questions',
        ),
    ]
