# Generated by Django 3.2.2 on 2021-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210509_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='number_of_questions',
            new_name='number_of_question',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score_to_pass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(),
        ),
    ]
