# Generated by Django 3.2.3 on 2021-05-19 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.BooleanField(default=False),
        ),
    ]
