# Generated by Django 3.2 on 2021-05-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_quiz_type'),
        ('quiz', '0007_alter_quiz_quiz_type'),
    ]

    operations = [
    ]
