# Generated by Django 3.2.2 on 2021-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiples', 'multiples'), ('True or False', 'True or False')], max_length=255),
        ),
    ]
