# Generated by Django 3.2.2 on 2021-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple', 'multiple'), ('True or False', 'True or False')], max_length=255),
        ),
    ]
